version: '3.8'
services:
  api:
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:p4ssw0rd@db:5432/db
      - NODE_ENV=development
      - PORT=3000
    ports:
      - '3000:3000'
      - '9229:9229'
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:12
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=p4ssw0rd
      - POSTGRES_DB=db
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', "sh -c 'pg_isready -U postgres -d db'"]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  pg-data:
